
name: Nitter Check

on:
  # JST 7時～23時 (UTC 22時～14時) の毎時0分
  schedule:
    - cron: "0 22-23 * * *"
    - cron: "0 0-14 * * *"

  workflow_dispatch:

jobs:
  nitter_job:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # リポジトリへのコミットを許可

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run Nitter scraper
        run: python nitter_scraper.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Commit updated found_snippets_nitter.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add found_snippets_nitter.json
          git commit -m "Update found_snippets_nitter.json" || echo "No changes to commit."
          git push
